# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-18 08:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20170518_0828'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='description',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
    ]
