# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-18 09:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_venue_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='atmosphere',
            field=models.CharField(default='', max_length=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='venue',
            name='emoji',
            field=models.CharField(default=':)', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='venue',
            name='loudness',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
